config/routes.rb
Cats::Application.routes.draw do

  resources :cats
  resources :cat_rental_requests
  resources :users, only: [:new, :create]
  resource  :sessions

  match '/cats_rental_request/:id/approve', to: 'cat_rental_requests#approve', via: [:patch], as: 'approve_request'

  match '/cats_rental_request/:id/deny', to: 'cat_rental_requests#deny', via: [:patch], as: 'deny_request'

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: [ "PENDING", "APPROVED", "DENIED"]  }

  validate :overlapping_approved_requests

  belongs_to :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id


  def approve!
    ActiveRecord::Base.transaction do
      self.update_attributes(status: "APPROVED")
      overlapping_pending_requests.each do |pending_request|
        pending_request.deny!
      end
    end
  end

  def deny!
    self.update_attributes(status: "DENIED")
  end

  def overlapping_pending_requests
    requests = overlapping_requests
    pending_overlapping_requests = requests.select do |req|
      req.status == "PENDING"
    end
  end

 # private
  def overlapping_approved_requests
    requests = overlapping_requests
    approved_overlapping_requests = requests.select do |req|
      req.status == "APPROVED" && self.id != req.id
    end

    if approved_overlapping_requests.length > 0
      # self.deny!
      errors[:base] << "There is an overlapping rental."
    end
  end

  def overlapping_requests
    start_date = self.start_date
    end_date = self.end_date
    cat_id = self.cat_id
    request_id = self.id

    potential_overlaps = CatRentalRequest.find_by_sql([<<-SQL, request_id: request_id, start_date: start_date, end_date: end_date, cat_id: cat_id ] )

      SELECT
        c.*
      FROM
        cat_rental_requests c
      WHERE
        c.id <> :request_id
        AND
          c.cat_id = :cat_id
        AND (
          (c.start_date BETWEEN :start_date AND :end_date) OR
          (c.end_date BETWEEN :start_date AND :end_date)
        ) OR (
          (:start_date BETWEEN c.start_date AND c.end_date) OR
          (:end_date BETWEEN c.start_date AND c.end_date)
        )
    SQL
  end

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_action :ensure_is_owner, only: [:approve, :deny]

  def index
    @cat_rental_requests = CatRentalRequest.all
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end

  def new
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to "/cat_rental_requests"
    else
      render json: @cat_rental_request.errors.full_messages
    end
  end

  def edit
    @cat_rental_requests = CatRentalRequest.all
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end

  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.update_attributes(cat_params)
      redirect_to "/cats"
    else
      render json: @cat_rental_request.errors.full_messages
    end
  end

  def approve
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.approve!

    redirect_to cats_path
  end

  def deny
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.deny!

    redirect_to cats_path
  end


  private
  def cat_rental_request_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date, :status)
  end

  def ensure_is_owner
    flash[:errors] = "You can't approve or deny rentals for cats you don't own."
    redirect_to cats_url if Cat.find(params[:id]).user_id != current_user.id
  end

end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/_form.html.erb
<p><%= link_to ("Back to the Rental index"), "/rentals"  %><p>
	<h1><%=@cat_rental_request.id %></h1>

	<form action="/cat_rental_requests/<%=@cat_rental_request.id%>" method="POST">

		<% if @cat_rental_request.persisted? %>
		<input type="hidden" name="_method" value="PATCH" >
		<% end %>

		<input type="hidden"
					 name="authenticity_token"
					 value="<%= form_authenticity_token %>" >

		<label for="rental_name">Select your Cat: </label>
		<select name="rental[cat_id]">
			<% @cats.each do |cat| %>
			<option name="rental[cat_id]" value="<%= cat.id %>" >
				"<%= cat.name %>"
			</option>
			<% end %>
		</select>

		<label for="rental_start_date">When do you want to rent from?</label>
		<input type="date" name="rental[start_date]" >

		<label for="rental_end_date">When do you want to rent until?</label>
		<input type="date" name="rental[end_date]" >


		<input type="submit" value:"Rent this cat!">
	</form>

app/views/cat_rental_requests/edit.html.erb
<%= render partial: "form", object: @cat_rental_request %>

app/views/cat_rental_requests/index.html.erb
<head>
	<title>
		Rentals
	</title>
</head>
<body>
	<h1>These are our cat rentals - index</h1>

				<% @cat_rental_requests.each do |rental| %>
				<p>Our cat <%=rental.cat.name%> is rented:</p>
				<ul>
					<li>From <%=rental.start_date%></li>
					<li>Until <%=rental.end_date%></li>
				</ul>
				<% end %>
	<p><%= link_to "Rent a Cat", new_cat_rental_request_path %>


</body>

app/views/cat_rental_requests/new.html.erb
<%= render partial: "form", object: @cat_rental_requests %>