config/routes.rb
Cats::Application.routes.draw do

  resources :cats
  resources :cat_rental_requests
  resources :users, only: [:new, :create]
  resource  :sessions

  match '/cats_rental_request/:id/approve', to: 'cat_rental_requests#approve', via: [:patch], as: 'approve_request'

  match '/cats_rental_request/:id/deny', to: 'cat_rental_requests#deny', via: [:patch], as: 'deny_request'

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  has_many :rentals,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy

    belongs_to :owner,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: "User"

  validates :age, :birthdate, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: [ "M", "F"]  }
  validates :color, inclusion: { in: [ "calico", "tabby", "solid"]  }
  validates :age, numericality: true

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :ensure_is_owner, only: [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @rental_requests = CatRentalRequest.where(cat_id: params[:id])
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    p = current_user.id
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to "/cats"
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to "/cats"
    else
      render json: @cat.errors.full_messages
    end
  end


  private
  def cat_params
    params.require(:cat).permit(:name, :color, :age, :birthdate, :sex)
  end

  def ensure_is_owner
    flash[:errors] = "You don't own that cat!"
    redirect_to cats_url if Cat.find(params[:id]).user_id != current_user.id
  end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<head>
	<title>
		Cats | Edit
	</title>
</head>
<body>
	<p><%= link_to ("Back to the cats index"), "/cats"  %><p>
	<h1><%=@cat.name %></h1>
		<form action="/cats/<%=@cat.id%>" method="POST">
		<% if @cat.persisted? %>
    	<input type="hidden" name="_method" value="PATCH" >
		<% end %>

		<input type="hidden"
					 name="authenticity_token"
					 value="<%= form_authenticity_token %>" >

			<label for="cat_name">Name</label>
			<input type="text" name="cat[name]" value="<%= @cat.name %>" >

			<label for="cat_color">Color</label>
			<select name="cat[color]">
				<option value="calico" <%="selected" if @cat.color=="calico"%>>Calico</option>
				<option value="tabby" <%="selected" if @cat.color=="tabby"%>>Tabby</option>
				<option value="solid"<%="selected" if @cat.color=="solid"%>>Solid</option>
			</select>

			<label for="cat_birthdate">Birthdate</label>
			<input type="date" name="cat[birthdate]" value="<%= @cat.birthdate %>" >

			<label for="cat_age">Age</label>
			<input type="number" name="cat[age]" min="0" max="1000" value="<%= @cat.age %>" >

			<label for="cat_sex">Sex</label>
			<select name="cat[sex]">
				<option value="M"<%="selected" if @cat.sex=="M"%>>Male</option>
				<option value="F"<%="selected" if @cat.sex=="F"%>>Female</option>
			</select>

			<input type="submit" value:"Edit this cat!">
		</form>
</body>


<!-- current_user.user_name -->

app/views/cats/edit.html.erb
<%= render partial: "form", object: @cat %>

app/views/cats/index.html.erb
<head>
	<title>
		Cats | Index
	</title>
</head>
<body>
	<h1>This is the Index</h1>
	<p><%= link_to ("Click here to create a new cat"), "cats/new" if current_user.present? %><p>
	<table>
	<% @cats.each do |cat| %>
		<tr>
			<td><%= link_to ("Name: #{cat.name}"), cat_url(cat) %></td>
			<td>Color: <%= cat.color%></td>
			<td>Age: <%= cat.age%></td>
			<td>Sex: <%= cat.sex%></td>
			<td>Birthdate: <%= Date.parse(cat.birthdate)%></td>
		</tr>
	<% end %>
	</table>
</body>

app/views/cats/new.html.erb
<%= render partial: "form", object: @cat %>

app/views/cats/show.html.erb
<h1>This is the Show view</h1>
<p><%= link_to ("Back to the cats index"), "/cats"  %><p>
<table>
	<tr>
		<!-- name -->
		<td>Name: <%= @cat.name%></td>
		<!-- color -->
		<td>Color: <%= @cat.color%></td>
		<!-- age -->
		<td>Age: <%= @cat.age%></td>
		<!-- sex -->
		<td>Sex: <%= @cat.sex%></td>
		<!-- birthdate -->
		<td>Birthdate: <%= Date.parse(@cat.birthdate) %></td>
		<!-- cat owner -->
		<td>Owner Name: <%= @cat.user_id.nil? ? "I have no owner" : User.find_by_id(@cat.user_id).user_name %></td>

	</tr>
	<% @rental_requests.each do |req| %>
	<tr>
		<td>
			<%= req.cat.name %> requested from <%= req.start_date %> to <%= req.end_date %>.
		</td>
		<td>This request is: <%= req.status %>. </td>

		<% if current_user.present? && current_user.id == @cat.user_id %>
		<td><%= button_to "Approve", approve_request_path(req),
																											method: "patch" %> </td>
		<td><%= button_to "Deny", deny_request_path(req), method: "patch" %> </td>
		<% end %>
	</tr>
	<% end %>
</table>

<p>
	<%= link_to "Rent this cat!", new_cat_rental_request_url if current_user.present? %>
</p>
<p>
	<%= link_to "Edit this cat!", edit_cat_url(@cat) if current_user.present? && current_user.id == @cat.user_id %>
</p>